### ISSUE TITLE
Comparison with reveal.js

### ISSUE THREAD

**Issue by donquixote** [gnab/remark#363] opened 2016-09-07 19:32 UTC
Hi,
as someone just looking for a suitable presentation tool, I am wondering what is the difference between remark and reveal.js, and when or why one would choose one over the other.

Maybe it is not your job as a project maintainer to write an objective comparison.. but maybe you can point out design goals that distinguish it from other solutions.

For now I am choosing remark because it seems to be simpler. But I did not spend enough time looking at the alternatives, to know whether this assessment is justified.

Thanks a lot!

**Comment by gnab** [comment] 2016-09-23 21:46
The two have a lot of similarities, but in terms of the content you're going to present I would say that reveal is perfect for creating elevator pitch style slideshows with large headings and eye catching effects, whereas remark is more generic and excellent for academic style slideshows where the content is more important than the way it is presented.

In terms of authoring slideshows, only reveal has an online editor, but if you're going to write the slideshow yourself, the key difference is that reveal uses _HTML_ and allows you to use markdown on a per-slides basis, while remark uses _markdown_ and allows you to use HTML if needed. So with reveal you have to create a pair of `<section>`/`</section>` tags per slide in which you write even more HTML formatted content, while with remark you simply write markdown and use a separator line containing three dashes (`---`) to create a new slide. IMHO the latter is a lot simpler and cleaner, unless you do all your work in the online editor of course. remark's fundamental focus on markdown is probably also it's most distinguishable feature. 

Thanks for choosing remark :)

**Comment by donquixote** [comment] 2016-09-23 21:51
Ok, sounds reasonable!
I think i can confirm most of what you say about remark, having made the slideshow and given the presentation two weeks ago.

I cannot say much about reveal.js, because I have not really tried it yet. So I am taking your word for it :)

**Comment by tbfe-de** [comment] 2016-10-26 08:28
Having written a lot of my teaching material (for C++ trainings) with `remark` since some time, I'm still watching both, `remark` and `reveal` for future developments. Each has its strength and weakness, but just for fairness I need to correct one of the statements made above:

It is **very well possible** to write a `reveal` presentation in "one large flow" of Markdown syntax - or store your Markdown in a separate file, if you run from a (local) server - and simply separate "horizontal" and "vertical" pages with different markers, like e.g. `===` and `---` (and you can set these markers freely to your liking; same for the start of an optional "Notes" section).

**Comment by rpietro** [comment] 2017-01-21 14:00
Just to add to the discussion, it's possible to write reveal using R markdown, and so entirely in markdown http://rmarkdown.rstudio.com/revealjs_presentation_format.html

**Comment by abelards** [comment] 2019-12-30 10:47
Do you think this is worth a wiki page?
Obviously both work well and it's a tradeoff on simplicity/features.

I'm not sure some info from 2016 is still relevant so I'm closing this and we can work together a wiki page if someone is up for the task.

**Closed by abelards** 2019-12-30 10:47 UTC

**Comment by sk1ll10** [comment] 2021-09-15 06:53
i know that the issue is closed but just another remark -> there is also reveal.md that can use plain markdown https://github.com/webpro/reveal-md. I have been using this in the past years but am now checking out remark.
